<?php
/**
 * @file
 * Core functions of this module.
 */

/**
 * Implements hook_theme().
 */
function tripal_jbrowse_theme($existing, $type, $theme, $path) {

  $items = array(
    'node__jbrowse_instance' => array(
      // Don't specify the path in the template name.
      // Unless you have your template inside a directory within this module.
      'template' =>  'theme/node--jbrowse-instance',
      'variables' => array('node' => (object)array()),
    ),
  );

  return $items;
}